### ISSUE TITLE
Sample NSF files?

### ISSUE THREAD

**Issue by mindscratch** [libyal/libnsfdb#6]
Are there sample NSF files somewhere in this project that I'm missing?

**Comment by joachimmetz** [comment]
From: https://github.com/libyal/libnsfdb/wiki/Testing#test-files

```
Note that no test files are provided by the project.
```

**Comment by joachimmetz** [comment]
And from https://github.com/libyal/libnsfdb/blob/main/README

```
Note that this project currently only focuses on the analysis of the format.
```

**Comment by joachimmetz** [comment]
@mindscratch if you can more context on why you want test data. Otherwise I consider this question answered

**Comment by mindscratch** [comment]
Joachim, thanks, I did look around but missed the "Testing" page. Mostly
interested in test data to better understand the format and perhaps try
some tools for reading/looking at it.
