### ISSUE TITLE
How do I run build.ps1?

### ISSUE THREAD

**Issue by EccentricVamp** [libyal/libnsfdb#8]
**Environment**
* Windows: 10.0.20348
* PowerShell: 7.2.2
* Python: 3.10.4

**Unexpected behavior**
Running `PS D:\Code\libnsfdb> .\build.ps1` returns `Missing Python: C:\Python37\python.exe`

It's pretty obvious what the issue is, but I read through the entirety of https://github.com/libyal/libnsfdb/wiki/Building and found no mention of any specific version of Python.

**Comment by EccentricVamp** [comment]
I'm going to try editing the build script and see if that works

**Comment by joachimmetz** [comment]
As I said previously this is a still experimental script also (per README) `Note that this project currently only focuses on the analysis of the format.`

**Comment by joachimmetz** [comment]
Closing issue, since script is WIP

**Comment by EccentricVamp** [comment]
So I shouldn't use the script?

**Comment by joachimmetz** [comment]
As I indicated, the script is WIP, if you want to use it, use it, but you'll need to go beyond the documentation and check the script what is needed. Also expect this project to provide mostly means to debug the file format of NFS database files, nothing fancy.
